POST http://localhost:5284/products
Content-Type: application/json

{
  "name": "Laptop2",
  "description": "Gaming laptop",
  "price": 5000,
  "currency": "TRY"
}

###

GET http://localhost:5284/products/d9f25a9e-68ff-4ba1-93fc-d5d3a24ef0fe

###

GET http://localhost:5284/products?page=1&pageSize=5&sortBy=price&sortDirection=desc
