POST http://localhost:5284/products
Content-Type: application/json

{
  "name": "Laptop",
  "description": "Gaming laptop",
  "price": 45000,
  "currency": "TRY"
}

###

GET http://localhost:5284/products/00000000-0000-0000-0000-000000000000
